# Generated by Django 4.1.1 on 2022-09-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_a_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50)),
                ('bcode', models.IntegerField(default=0)),
                ('add_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Delete_a_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50)),
                ('bcode', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Get_all_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Update_an_entry_of_a_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=50)),
                ('bcode', models.IntegerField(default=0)),
                ('issuedate', models.DateField()),
            ],
        ),
    ]
