# Generated by Django 4.1.1 on 2022-09-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='get_all_book',
            name='bcode',
            field=models.IntegerField(default=0),
        ),
    ]
